SmartQsort
AlexPoziev/SpbuHomework pull request #2
Opened 2022-09-22 21:29 UTC by AlexPoziev

2022-10-22 13:22 UTC, yurii-litvinov requested changes
Одного .c-файла недостаточно, надо выкладывать файлы с конфигурацией сборки ещё (в зависимости от того, чем Вы пользуетесь, конфиги CMake или .sln/.vcxproj)

2022-10-22 13:22 UTC, yurii-litvinov commented on Homework3/smartQsort.c
> +    srand((unsigned)time(0));
```suggestion
    srand((unsigned)time(NULL));
```
time указатель принимает

2022-10-22 13:22 UTC, yurii-litvinov commented on Homework3/smartQsort.c
> +int semiQsort(int low, int high, int array[]) {
Это стоит переименовать во что-нибудь более традиционное, типа partition или что-то такое

2022-10-22 13:22 UTC, yurii-litvinov commented on Homework3/smartQsort.c
> +        swap(&array[low], &array[border]);;
```suggestion
        swap(&array[low], &array[border]);
```

2022-10-22 13:22 UTC, yurii-litvinov commented on Homework3/smartQsort.c
> +    if (!(low == high)) {
```suggestion
    if (low != high) {
```

2022-10-22 13:22 UTC, yurii-litvinov commented on Homework3/smartQsort.c
> +    return differentNumbers == sortedDifferentNumbers ? true : false;
```suggestion
    return differentNumbers == sortedDifferentNumbers;
```

2022-10-23 19:31 UTC, AlexPoziev commented
Вы разрешили на 2-3 домашней работе отправлять .c файл. Дальше уже CMake на месте:)

2022-11-11 16:29 UTC, merged